### PR TITLE
Updated to version 4.1.0 and added a new class for installing language packs

### PR DESCRIPTION
**Pull request by magicmonty**
The current stable version is 4.1.0, so I bumped the Version up.
Also there was no ability to install additional language packs, so I added a new class `libreoffice::languagepack`

Usage of the languagepack class: 

``` puppet
include libreoffice::languagepack
```

which includes the default language (German), or get your own laguage as follows:

``` puppet
class { 'libreoffice::languagepack':
  locale => 'fr',
}
```

### CODE REVIEW

**Comment by jasonamyers** [comment]
Thank you very much for the PR!

**Comment by magicmonty** [comment]
You're welcome ;)

**Comment by magicmonty** [comment]
Could you please tag it to 4.1.0?

**Comment by jasonamyers** [comment]
done and done

**Comment by magicmonty** [comment]
Thanks

**Pull request merged**
